"""
ICD-10 code to English name mapping for the bone/orthopedics benchmark.

Provides `build_icd_mapping()` which returns:
  - code_to_english : dict[str, str]   – ICD code → English disease name
  - code_to_chapter : dict[str, str]   – ICD code → chapter English name
"""

from __future__ import annotations

import os
import re
import pandas as pd
from typing import Dict, Tuple

# ── paths ────────────────────────────────────────────────────────────────
_BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_CODE_COUNTS = os.path.join(_BASE, "data", "stat", "all", "code_counts.csv")
_SPLIT_STATS = os.path.join(_BASE, "gen_validation", "test_final", "split_stats_by_code.csv")

# ── ICD-10 chapter mapping ──────────────────────────────────────────────
_CHAPTER_MAP: Dict[str, str] = {
    "M": "Musculoskeletal & connective tissue",
    "S": "Injuries (single body region)",
    "D": "Neoplasms & blood disorders",
    "C": "Malignant neoplasms",
    "T": "Injuries (multiple) & complications",
    "Q": "Congenital malformations",
    "R": "Symptoms & signs",
    "G": "Nervous system diseases",
    "L": "Skin & subcutaneous tissue",
    "A": "Infectious diseases",
    "Z": "Health services contact",
    "E": "Endocrine & metabolic",
    "I": "Circulatory system",
    "J": "Respiratory system",
    "K": "Digestive system",
    "F": "Mental & behavioral",
}

# ── Hard-coded fallback for codes that have no Chinese name ─────────────
_HARDCODED: Dict[str, str] = {
    "C40.200":      "Malignant neoplasm of long bones, lower limb",
    "G60.003":      "Hereditary motor and sensory neuropathy",
    "M13.900C":     "Arthritis, unspecified",
    "M16.900":      "Coxarthrosis, unspecified",
    "M17.900":      "Gonarthrosis, unspecified",
    "M19.901":      "Arthrosis, ankle",
    "M19.905":      "Arthrosis, elbow",
    "M19.906":      "Arthrosis, shoulder",
    "M20.100X002":  "Hallux valgus",
    "M24.002":      "Loose body in joint, shoulder",
    "M51.202":      "Lumbar disc herniation",
    "M75.000":      "Adhesive capsulitis of shoulder",
    "M87.002":      "Osteonecrosis, femoral head",
    "R22.400X002":  "Soft tissue mass, lower limb",
    "S46.002":      "Injury of tendon, shoulder level",
    "S52.801":      "Fracture of forearm, unspecified",
    "S72.000":      "Fracture of neck of femur",
    "S72.101":      "Pertrochanteric fracture",
    "S82.101":      "Fracture of proximal tibia",
    "S82.301":      "Fracture of lower end of tibia",
    "Z47.001":      "Removal of internal fixation device",
}

# ── Chinese → English dictionary (longest-match first) ──────────────────
# Order matters: longer terms must come before shorter sub-terms so that
# e.g. "椎间盘突出" is matched before "椎间" or "盘".

_ZH_EN: list[tuple[str, str]] = [
    # ── very specific compound terms (must match before parts) ───
    ("术后切口脂肪液化", "postoperative incisional fat liquefaction"),
    ("术后切口感染", "postoperative incision infection"),
    ("术后伤口愈合不良", "postoperative wound healing failure"),
    ("自主神经", "autonomic nerve"),
    ("交搭跨越", "overlapping"),
    ("轻链型", "light chain type"),
    ("轻链", "light chain"),
    ("脂肪液化", "fat liquefaction"),
    ("舟舟状", "scaphoid"),
    ("腓胫", "fibular and tibial"),
    ("手舟", "hand scaphoid"),
    ("腓", "fibular"),
    ("胫", "tibial"),
    ("组织良性", "tissue benign"),
    ("良性脂肪瘤样", "benign lipomatous"),
    ("肌内", "intramuscular"),
    ("巨大", "massive"),
    ("钙盐沉着", "calcium deposition"),
    ("掌关节", "carpometacarpal joint"),
    ("副韧带", "collateral ligament"),
    ("变性", "degeneration"),
    ("僵硬", "stiffness"),
    ("腱膜", "aponeurosis"),
    ("跖筋膜", "plantar fascia"),
    ("破坏", "destruction"),
    ("副舟骨", "accessory navicular bone"),
    ("幼年型", "juvenile"),
    ("剥脱性骨软骨炎", "osteochondritis dissecans"),
    ("剥脱", "dissecting"),
    ("并指", "syndactyly of fingers"),
    ("并趾", "syndactyly of toes"),
    ("并", "syn-"),
    ("短小缺陷", "shortening defect"),
    ("半椎体", "hemivertebra"),
    ("腰化", "lumbarization"),
    ("纤维", "fibrous"),
    ("非恶性", "non-malignant"),
    ("恶", "malignant"),
    ("舟状", "scaphoid"),
    ("长头", "long head"),
    ("腱", "tendon"),
    ("桶柄状", "bucket-handle"),
    ("结构", "structural"),
    ("完全", "complete"),
    ("固定", "fixation"),
    ("切口", "incision"),
    ("愈合不良", "poor healing"),
    ("组织", "tissue"),

    # ── multi-word compound terms (longest first) ───
    ("骨纤维异常增殖症", "fibrous dysplasia of bone"),
    ("骨纤维异样增殖症", "fibrous dysplasia of bone"),
    ("多骨纤维性结构不良", "polyostotic fibrous dysplasia"),
    ("骨纤维性结构不良", "fibrous dysplasia of bone"),
    ("纤维性结构不良", "fibrous dysplasia"),
    ("纤维结构不良", "fibrous dysplasia"),
    ("骨纤维结构不良", "fibrous dysplasia of bone"),
    ("色素沉着绒毛结节性", "pigmented villonodular"),
    ("绒毛结节性", "villonodular"),
    ("朗格汉斯细胞组织细胞", "Langerhans cell histiocytosis"),
    ("嗜酸细胞肉芽肿", "eosinophilic granuloma"),
    ("嗜酸性肉芽肿", "eosinophilic granuloma"),
    ("骨嗜酸细胞性肉芽肿", "eosinophilic granuloma of bone"),
    ("窦组织细胞增多", "sinus histiocytosis"),
    ("弥漫大B细胞", "diffuse large B-cell"),
    ("骨孤立性浆细胞瘤", "solitary plasmacytoma of bone"),
    ("浆细胞瘤", "plasmacytoma"),
    ("恶性黑色素瘤", "malignant melanoma"),
    ("原位黑色素瘤", "melanoma in situ"),
    ("海绵状淋巴管瘤", "cavernous lymphangioma"),
    ("淋巴管瘤", "lymphangioma"),
    ("内皮瘤", "endothelioma"),
    ("错构瘤", "hamartoma"),
    ("垂体瘤", "pituitary tumor"),
    ("球瘤", "glomus tumor"),
    ("皮脂腺", "sebaceous"),
    ("表皮", "epidermal"),
    ("粘液囊", "mucous bursa"),
    ("赘生物", "growth"),

    # ── body parts / bones (long → short) ───
    ("肩胛骨", "scapula"),
    ("肩胛下肌", "subscapularis"),
    ("肩胛盂前下方", "anteroinferior glenoid"),
    ("肩胛盂前后方的", "anteroposterior glenoid"),
    ("肩胛区", "scapular region"),
    ("肩胛", "scapula"),
    ("股骨头", "femoral head"),
    ("股骨颈", "femoral neck"),
    ("股骨干", "femoral shaft"),
    ("股骨远端", "distal femur"),
    ("股骨近端", "proximal femur"),
    ("股骨", "femur"),
    ("胫骨平台", "tibial plateau"),
    ("胫骨远端", "distal tibia"),
    ("胫骨近端", "proximal tibia"),
    ("胫腓骨干", "tibial and fibular shaft"),
    ("胫腓远端", "distal tibiofibular"),
    ("胫腓骨", "tibia and fibula"),
    ("胫腓", "tibiofibular"),
    ("胫骨", "tibia"),
    ("胫后", "posterior tibial"),
    ("腓总神经", "common peroneal nerve"),
    ("腓浅", "superficial peroneal"),
    ("腓神经", "peroneal nerve"),
    ("腓肠肌", "gastrocnemius"),
    ("腓肠", "gastrocnemius"),
    ("腓骨", "fibula"),
    ("肱二头肌长头", "long head of biceps"),
    ("肱二头肌", "biceps brachii"),
    ("肱骨近端", "proximal humerus"),
    ("肱骨远端", "distal humerus"),
    ("肱骨髁上", "supracondylar humerus"),
    ("肱骨髁间", "intercondylar humerus"),
    ("肱骨外上髁", "lateral epicondyle of humerus"),
    ("肱骨外科颈", "surgical neck of humerus"),
    ("肱骨大结节", "greater tuberosity of humerus"),
    ("肱骨内髁", "medial condyle of humerus"),
    ("肱骨干", "humeral shaft"),
    ("肱骨上端", "proximal humerus"),
    ("肱骨下端", "distal humerus"),
    ("肱骨", "humerus"),
    ("桡骨远端", "distal radius"),
    ("桡骨头", "radial head"),
    ("桡骨下端", "distal radius"),
    ("桡骨", "radius"),
    ("尺骨鹰嘴", "olecranon"),
    ("尺骨茎突", "ulnar styloid"),
    ("尺骨远端", "distal ulna"),
    ("尺骨近端", "proximal ulna"),
    ("下尺桡", "distal radioulnar"),
    ("尺桡", "radioulnar"),
    ("尺骨", "ulna"),
    ("锁骨肩峰端", "acromial end of clavicle"),
    ("锁骨干", "clavicle shaft"),
    ("锁骨", "clavicle"),
    ("髌骨", "patella"),
    ("跟骨", "calcaneus"),
    ("距腓前", "anterior talofibular"),
    ("距舟", "talonavicular"),
    ("距骨", "talus"),
    ("骨盆", "pelvis"),
    ("盆骨", "pelvis"),
    ("盆腔", "pelvic cavity"),
    ("髂骨", "ilium"),
    ("坐骨", "ischium"),
    ("耻骨分支", "pubic ramus"),
    ("耻骨", "pubis"),
    ("肋骨", "rib"),
    ("胸骨", "sternum"),
    ("颅骨", "skull"),
    ("下颌骨", "mandible"),
    ("上颌骨", "maxilla"),
    ("鼻骨", "nasal bone"),
    ("舟状骨", "navicular bone"),
    ("舟骨", "navicular bone"),
    ("楔状骨", "cuneiform bone"),
    ("月骨", "lunate bone"),
    ("三角骨", "triquetral bone"),
    ("钩骨", "hamate bone"),
    ("头状骨", "capitate bone"),
    ("大多角骨", "trapezium bone"),
    ("小多角骨", "trapezoid bone"),
    ("豆状骨", "pisiform bone"),
    ("腕骨", "carpal bone"),
    ("掌骨基底", "metacarpal base"),
    ("掌骨干", "metacarpal shaft"),
    ("掌骨", "metacarpal"),
    ("跖跗", "tarsometatarsal"),
    ("跗跖", "tarsometatarsal"),
    ("跖骨基底", "metatarsal base"),
    ("跖骨", "metatarsal"),
    ("趾骨", "toe phalanx"),
    ("指骨近节", "proximal phalanx"),
    ("指骨中节", "middle phalanx"),
    ("指骨", "finger phalanx"),
    ("跗骨", "tarsal bone"),
    ("骶尾部", "sacrococcygeal"),
    ("骶椎骨", "sacral vertebra"),
    ("骶椎", "sacral vertebra"),
    ("骶骨", "sacrum"),
    ("骶部", "sacral region"),
    ("骶", "sacral"),
    ("尾骨", "coccyx"),
    ("寰枢椎", "atlantoaxial"),
    ("寰椎", "atlas (C1)"),
    ("枢椎", "axis (C2)"),
    ("颈椎间盘突出", "cervical disc herniation"),
    ("颈椎", "cervical spine"),
    ("胸椎", "thoracic spine"),
    ("腰骶", "lumbosacral"),
    ("腰椎", "lumbar spine"),
    ("椎骨", "vertebra"),
    ("脊椎", "spine"),
    ("脊柱", "spine"),
    ("椎体", "vertebral body"),
    ("椎弓根", "pedicle"),
    ("椎板", "lamina"),
    ("棘突", "spinous process"),
    ("横突", "transverse process"),
    ("椎管内外", "intraspinal and extraspinal"),
    ("椎管内", "intraspinal"),
    ("齿状突", "odontoid process"),

    # ── joints ───
    ("踝关节", "ankle joint"),
    ("髋关节", "hip joint"),
    ("膝关节", "knee joint"),
    ("肩关节盂唇", "shoulder labrum"),
    ("肩关节", "shoulder joint"),
    ("肘关节", "elbow joint"),
    ("腕关节", "wrist joint"),
    ("指间关节", "interphalangeal joint"),
    ("掌指关节", "metacarpophalangeal joint"),
    ("跖趾关节", "metatarsophalangeal joint"),
    ("胸锁关节", "sternoclavicular joint"),
    ("肩锁关节", "acromioclavicular joint"),
    ("骶髂关节", "sacroiliac joint"),
    ("距下", "subtalar"),
    ("髋臼", "acetabulum"),
    ("关节内", "intra-articular"),
    ("关节面", "articular surface"),
    ("关节囊", "joint capsule"),
    ("关节腔", "joint cavity"),
    ("关节", "joint"),
    ("盂唇", "labrum"),

    # ── soft-tissue structures ───
    ("前交叉韧带", "anterior cruciate ligament"),
    ("后交叉韧带", "posterior cruciate ligament"),
    ("后纵韧带", "posterior longitudinal ligament"),
    ("三角韧带", "deltoid ligament"),
    ("三角纤维", "triangular fibrocartilage"),
    ("侧副韧带", "collateral ligament"),
    ("十字韧带", "cruciate ligament"),
    ("黄韧带", "ligamentum flavum"),
    ("韧带", "ligament"),
    ("半月板后角", "posterior horn of meniscus"),
    ("半月板", "meniscus"),
    ("跟腱", "Achilles tendon"),
    ("掌腱膜", "palmar aponeurosis"),
    ("冈上肌", "supraspinatus"),
    ("肱二", "biceps"),
    ("肌腱", "tendon"),
    ("腱鞘", "tendon sheath"),
    ("滑膜", "synovium"),
    ("滑囊", "bursa"),
    ("筋膜", "fascia"),
    ("软骨", "cartilage"),
    ("肌肉", "muscle"),
    ("神经根", "nerve root"),
    ("神经丛", "nerve plexus"),
    ("臂丛神经", "brachial plexus nerve"),
    ("臂丛", "brachial plexus"),
    ("坐骨神经", "sciatic nerve"),
    ("桡神经", "radial nerve"),
    ("尺神经", "ulnar nerve"),
    ("正中神经", "median nerve"),
    ("周围神经", "peripheral nerve"),
    ("神经鞘", "nerve sheath"),
    ("神经", "nerve"),
    ("血管", "blood vessel"),
    ("动脉", "artery"),
    ("静脉", "vein"),
    ("皮肤", "skin"),
    ("皮下", "subcutaneous"),
    ("软组织", "soft tissue"),
    ("结缔组织", "connective tissue"),
    ("骨膜", "periosteum"),
    ("骨髓", "bone marrow"),
    ("肩袖", "rotator cuff"),
    ("腘窝", "popliteal fossa"),
    ("臀肌", "gluteal muscle"),
    ("梨状肌", "piriformis"),

    # ── spine-specific conditions (must precede generic) ───
    ("间盘突出", "disc herniation"),
    ("椎间盘突出", "disc herniation"),
    ("椎间盘脱出", "disc extrusion"),
    ("椎间盘退行性变", "disc degeneration"),
    ("椎间盘退变", "disc degeneration"),
    ("间盘退行性", "disc degenerative"),
    ("间盘", "disc"),
    ("椎间盘", "intervertebral disc"),
    ("椎管狭窄", "spinal stenosis"),
    ("椎体滑脱", "spondylolisthesis"),
    ("椎间滑脱", "spondylolisthesis"),
    ("脊柱侧弯", "scoliosis"),
    ("脊柱侧凸", "scoliosis"),
    ("脊柱后凸", "kyphosis"),
    ("脊柱畸形", "spinal deformity"),
    ("椎体压缩性骨折", "vertebral compression fracture"),
    ("压缩性骨折", "compression fracture"),
    ("脊髓型颈椎病", "cervical spondylotic myelopathy"),
    ("神经根型颈椎病", "cervical spondylotic radiculopathy"),
    ("颈椎病", "cervical spondylosis"),
    ("脊髓损伤", "spinal cord injury"),
    ("脊髓", "spinal cord"),
    ("峡部裂", "spondylolysis"),
    ("滑脱", "spondylolisthesis"),

    # ── neoplasms (long → short) ───
    ("骨巨细胞瘤", "giant cell tumor of bone"),
    ("骨肉瘤", "osteosarcoma"),
    ("骨母细胞瘤", "osteoblastoma"),
    ("骨软骨瘤", "osteochondroma"),
    ("骨样骨瘤", "osteoid osteoma"),
    ("软骨肉瘤", "chondrosarcoma"),
    ("软骨母细胞瘤", "chondroblastoma"),
    ("软骨瘤", "chondroma"),
    ("脂肪肉瘤", "liposarcoma"),
    ("脂肪瘤", "lipoma"),
    ("血管肉瘤", "angiosarcoma"),
    ("血管瘤", "hemangioma"),
    ("淋巴瘤", "lymphoma"),
    ("骨髓瘤", "myeloma"),
    ("多发性骨髓瘤", "multiple myeloma"),
    ("纤维肉瘤", "fibrosarcoma"),
    ("纤维瘤", "fibroma"),
    ("神经鞘瘤", "schwannoma"),
    ("神经纤维瘤", "neurofibroma"),
    ("滑膜肉瘤", "synovial sarcoma"),
    ("平滑肌瘤", "leiomyoma"),
    ("横纹肌肉瘤", "rhabdomyosarcoma"),
    ("恶性肿瘤", "malignant neoplasm"),
    ("良性肿瘤", "benign neoplasm"),
    ("肿瘤", "neoplasm"),
    ("肿物", "mass"),
    ("肿块", "mass"),
    ("肿胀", "swelling"),
    ("囊肿", "cyst"),
    ("占位性病变", "space-occupying lesion"),
    ("占位", "space-occupying lesion"),
    ("转移瘤", "metastatic tumor"),
    ("转移", "metastasis"),
    ("交界性", "borderline"),

    # ── conditions / pathology ───
    ("骨质疏松", "osteoporosis"),
    ("骨质增生", "osteophyte"),
    ("骨质破坏", "bone destruction"),
    ("骨质", "bone"),
    ("骨髓炎", "osteomyelitis"),
    ("骨坏死", "osteonecrosis"),
    ("缺血性坏死", "avascular necrosis"),
    ("骨囊肿", "bone cyst"),
    ("骨不连", "nonunion"),
    ("骨延迟愈合", "delayed union"),
    ("骨缺损", "bone defect"),
    ("骨外露", "bone exposure"),
    ("骨赘", "osteophyte"),
    ("骨疣", "exostosis"),
    ("外生骨疣", "exostosis"),
    ("骨性", "bony"),
    ("骨间", "interosseous"),
    ("骨干", "diaphysis"),
    ("骨折", "fracture"),
    ("骨裂", "fissure fracture"),
    ("骨", "bone"),
    ("脱位", "dislocation"),
    ("半脱位", "subluxation"),
    ("滑膜炎", "synovitis"),
    ("腱鞘炎", "tenosynovitis"),
    ("筋膜炎", "fasciitis"),
    ("滑囊炎", "bursitis"),
    ("骨关节炎", "osteoarthritis"),
    ("关节炎", "arthritis"),
    ("类风湿性", "rheumatoid"),
    ("类风湿", "rheumatoid"),
    ("痛风性", "gouty"),
    ("痛风", "gout"),
    ("强直性脊柱炎", "ankylosing spondylitis"),
    ("强直", "ankylosis"),
    ("肉芽肿", "granuloma"),

    # ── modifiers / qualifiers ───
    ("退行性病变", "degenerative disease"),
    ("退行性变", "degenerative change"),
    ("退行性", "degenerative"),
    ("退变", "degeneration"),
    ("先天性", "congenital"),
    ("后天性", "acquired"),
    ("创伤性", "traumatic"),
    ("创伤后", "post-traumatic"),
    ("病理性", "pathological"),
    ("陈旧性", "old"),
    ("新鲜", "acute"),
    ("急性", "acute"),
    ("亚急性", "subacute"),
    ("慢性", "chronic"),
    ("开放性", "open"),
    ("闭合性", "closed"),
    ("多发性", "multiple"),
    ("多发", "multiple"),
    ("复发性", "recurrent"),
    ("原发性", "primary"),
    ("继发性", "secondary"),
    ("继发", "secondary"),
    ("全身性", "systemic"),
    ("进行性", "progressive"),
    ("双侧", "bilateral"),
    ("单侧", "unilateral"),
    ("左侧", "left"),
    ("右侧", "right"),
    ("左", "left"),
    ("右", "right"),
    ("外侧", "lateral"),
    ("内侧", "medial"),
    ("上端", "proximal"),
    ("下端", "distal"),
    ("近端", "proximal"),
    ("远端", "distal"),
    ("前方", "anterior"),
    ("后方", "posterior"),
    ("前", "anterior"),
    ("后", "posterior"),
    ("外", "lateral"),
    ("内", "medial"),
    ("非", "non-"),
    ("无菌性", "aseptic"),
    ("化脓性", "suppurative"),
    ("硬化性", "sclerosing"),
    ("闭塞性", "obliterative"),
    ("药物性", "drug-induced"),
    ("酒精性", "alcoholic"),
    ("老年性", "senile"),
    ("绝经后", "postmenopausal"),
    ("青少年特发性", "adolescent idiopathic"),
    ("特发性", "idiopathic"),
    ("单骨性", "monostotic"),
    ("多骨", "polyostotic"),
    ("单一性", "solitary"),
    ("止点性", "insertional"),

    # ── procedures / devices / postop ───
    ("手术后", "postoperative"),
    ("术后恢复期", "postoperative recovery"),
    ("术后伤口愈合不良", "postoperative wound healing failure"),
    ("术后切口脂肪液化", "postoperative incisional fat liquefaction"),
    ("术后切口", "postoperative incision"),
    ("术前化疗", "preoperative chemotherapy"),
    ("术后化疗", "postoperative chemotherapy"),
    ("术后", "postoperative"),
    ("手术", "surgical"),
    ("内固定物植入", "internal fixation implant"),
    ("内固定术后", "post internal fixation"),
    ("内固定", "internal fixation"),
    ("外固定", "external fixation"),
    ("假体", "prosthesis"),
    ("植入物", "implant"),
    ("植入", "implant"),
    ("取除", "removal of"),
    ("取出", "removal of"),
    ("置换术", "replacement"),
    ("置换后", "post-replacement"),
    ("置换", "replacement"),
    ("关节置换", "arthroplasty"),
    ("融合术", "fusion"),
    ("截骨术", "osteotomy"),
    ("截断术残端的", "amputation stump"),
    ("切除术", "excision"),
    ("清创", "debridement"),
    ("化学治疗", "chemotherapy"),
    ("人工", "artificial"),
    ("装置", "device"),

    # ── anatomical regions ───
    ("上肢", "upper limb"),
    ("下肢", "lower limb"),
    ("四肢", "limbs"),
    ("肢体", "limb"),
    ("肢端", "acral"),
    ("前臂", "forearm"),
    ("上臂", "upper arm"),
    ("大腿", "thigh"),
    ("小腿", "lower leg"),
    ("足底内侧", "medial plantar"),
    ("足底外侧", "lateral plantar"),
    ("足底", "plantar"),
    ("足跟", "heel"),
    ("足掌", "sole"),
    ("足趾", "toe"),
    ("足部", "foot"),
    ("足", "foot"),
    ("手部", "hand"),
    ("手", "hand"),
    ("手指", "finger"),
    ("脚趾", "toe"),
    ("拇指", "thumb"),
    ("拇趾", "great toe"),
    ("小趾", "little toe"),
    ("腰部", "lumbar region"),
    ("腰大肌", "psoas major"),
    ("腰", "lumbar"),
    ("颈部", "cervical region"),
    ("颈", "cervical"),
    ("胸腔", "thoracic cavity"),
    ("胸壁", "thoracic wall"),
    ("胸部", "thoracic region"),
    ("胸", "thoracic"),
    ("腹壁", "abdominal wall"),
    ("腹膜后腔", "retroperitoneum"),
    ("腹膜后", "retroperitoneal"),
    ("腹股沟", "inguinal"),
    ("腹部", "abdominal"),
    ("腹", "abdomen"),
    ("肩峰", "acromion"),
    ("肩部", "shoulder region"),
    ("肩区", "shoulder region"),
    ("肩", "shoulder"),
    ("肘部", "elbow region"),
    ("肘", "elbow"),
    ("腕部", "wrist region"),
    ("腕", "wrist"),
    ("髋部", "hip region"),
    ("髋", "hip"),
    ("膝部", "knee region"),
    ("膝", "knee"),
    ("踝部", "ankle region"),
    ("踝", "ankle"),
    ("背部", "back region"),
    ("背", "back"),
    ("头", "head"),
    ("臀部", "buttock"),
    ("臀", "buttock"),
    ("腋下", "axillary"),
    ("腋", "axillary"),
    ("骶尾", "sacrococcygeal"),
    ("躯干", "trunk"),
    ("盆区", "pelvic region"),
    ("周围", "surrounding"),

    # ── other specific terms ───
    ("扁平足", "flat foot"),
    ("平足", "flat foot"),
    ("马蹄内翻足", "clubfoot"),
    ("马蹄内翻", "equinovarus"),
    ("马蹄足", "clubfoot"),
    ("高弓足", "pes cavus"),
    ("弓形足", "pes cavus"),
    ("弓形", "cavus"),
    ("拇外翻", "hallux valgus"),
    ("拇内翻", "hallux varus"),
    ("外翻", "valgus"),
    ("内翻", "varus"),
    ("内收", "adduction"),
    ("短缩", "shortening"),
    ("弯曲", "bowing"),
    ("缺如", "absence"),
    ("融合", "fusion"),
    ("联合", "coalition"),
    ("槌状指", "mallet finger"),
    ("锤状趾", "hammer toe"),
    ("爪形趾", "claw toe"),
    ("脚趾重叠", "overlapping toes"),
    ("扳机指", "trigger finger"),
    ("翼状", "winged"),
    ("盘状", "discoid"),
    ("踇囊炎", "bunion"),
    ("畸形", "deformity"),
    ("挛缩", "contracture"),
    ("粘连", "adhesion"),
    ("松解", "release"),
    ("松弛", "laxity"),
    ("松动", "loosening"),
    ("不稳定", "instability"),
    ("不稳", "instability"),
    ("不全脱位", "subluxation"),
    ("不全", "incomplete"),
    ("不完全性", "incomplete"),
    ("不完全", "incomplete"),
    ("狭窄", "stenosis"),
    ("损伤", "injury"),
    ("损害", "impairment"),
    ("断裂", "rupture"),
    ("撕裂", "tear"),
    ("撕脱", "avulsion"),
    ("挫伤", "contusion"),
    ("扭伤", "sprain"),
    ("劳损", "strain"),
    ("坏疽", "gangrene"),
    ("坏死", "necrosis"),
    ("感染性", "infectious"),
    ("感染", "infection"),
    ("炎症", "inflammation"),
    ("水肿", "edema"),
    ("积液", "effusion"),
    ("出血", "hemorrhage"),
    ("血肿", "hematoma"),
    ("疼痛", "pain"),
    ("麻木", "numbness"),
    ("麻痹", "paralysis"),
    ("无力", "weakness"),
    ("结核", "tuberculosis"),
    ("梅毒", "syphilis"),
    ("异物", "foreign body"),
    ("游离体", "loose body"),
    ("发育不良", "dysplasia"),
    ("发育不全", "hypoplasia"),
    ("增生", "hyperplasia"),
    ("萎缩", "atrophy"),
    ("肥大", "hypertrophy"),
    ("钙化性", "calcific"),
    ("钙化", "calcification"),
    ("异位骨化", "heterotopic ossification"),
    ("骨化性肌炎", "myositis ossificans"),
    ("非骨化性纤维瘤", "non-ossifying fibroma"),
    ("骨化", "ossification"),
    ("纤维化", "fibrosis"),
    ("腱鞘囊肿", "ganglion cyst"),
    ("腘窝囊肿", "popliteal cyst"),
    ("腕管综合征", "carpal tunnel syndrome"),
    ("肘管综合征", "cubital tunnel syndrome"),
    ("胸廓出口综合征", "thoracic outlet syndrome"),
    ("综合征", "syndrome"),
    ("综合症", "syndrome"),
    ("卡压征", "entrapment syndrome"),
    ("卡压", "entrapment"),
    ("疾患", "disorder"),
    ("疾病", "disease"),
    ("病变", "lesion"),
    ("病", "disease"),
    ("膝关节病", "gonarthrosis"),
    ("髋关节病", "coxarthrosis"),
    ("肩关节病", "shoulder arthropathy"),
    ("三踝", "trimalleolar"),
    ("双踝", "bimalleolar"),
    ("外踝", "lateral malleolus"),
    ("内踝", "medial malleolus"),
    ("后踝", "posterior malleolus"),
    ("髁间棘", "intercondylar eminence"),
    ("大粗隆", "greater trochanter"),
    ("转子间", "intertrochanteric"),
    ("粗隆下", "subtrochanteric"),
    ("髁上", "supracondylar"),
    ("髁间", "intercondylar"),
    ("髁", "condyle"),
    ("伴有", "with"),
    ("伴", "with"),
    ("合并", "with"),
    ("及", "and"),
    ("和", "and"),
    ("的", ""),
    ("或", "or"),
    ("其他", "other"),
    ("未特指", "unspecified"),
    ("不明", "unspecified"),
    ("后遗症", "sequelae"),
    ("后状态", "post-status"),
    ("连接不正", "malunion"),
    ("不连接", "nonunion"),
    ("延迟愈合", "delayed union"),
    ("累及", "involving"),
    ("累", "involving"),
    ("均", "both"),
    ("仅", "only"),
    ("多处", "multiple"),
    ("多部位", "multiple sites"),
    ("多向", "multidirectional"),
    ("多个并发症", "multiple complications"),
    ("局部肿胀", "localized swelling"),
    ("局部", "localized"),
    ("结节", "tubercle"),
    ("包括", "including"),
    ("部位", "site"),
    ("浅表", "superficial"),
    ("特指", "specified"),
    ("习惯性", "habitual"),
    ("复发", "recurrent"),
    ("痉挛性", "spastic"),

    # ── specific medical conditions ───
    ("性脓肿", "abscess"),
    ("肌间脓肿", "intermuscular abscess"),
    ("脓肿", "abscess"),
    ("夏科", "Charcot"),
    ("灰质炎瘫痪型", "poliomyelitis paralytic type"),
    ("胃", "gastric"),
    ("乙状结肠", "sigmoid colon"),
    ("直肠", "rectum"),
    ("胰体胰尾部", "body and tail of pancreas"),
    ("支气管或肺", "bronchus or lung"),
    ("支气管", "bronchial"),
    ("膜壁层", "parietal pleura"),
    ("长骨", "long bone"),
    ("短骨", "short bone"),
    ("肺", "lung"),
    ("脾破裂", "splenic rupture"),
    ("乳腺外上象限", "upper outer quadrant of breast"),
    ("乳腺", "breast"),
    ("鞘膜", "tunica vaginalis"),
    ("膀胱侧壁", "lateral wall of bladder"),
    ("淋巴结继发", "lymph node secondary"),
    ("淋巴结肿大", "lymphadenopathy"),
    ("淋巴结", "lymph node"),
    ("全身性广泛继发", "disseminated secondary"),
    ("膜瘘", "pleural fistula"),
    ("脓气", "pyopneumo"),
    ("色素沉着", "pigmented"),
    ("窦道", "sinus tract"),
    ("皱襞", "plica"),
    ("银屑", "psoriatic"),
    ("嵌甲", "ingrown nail"),
    ("趾甲沟炎", "paronychia of toe"),
    ("瘢痕", "scar"),
    ("性早熟", "precocious puberty"),
    ("内生", "enchondral"),
    ("马富奇", "Maffucci"),
    ("骨骼", "skeletal"),
    ("高血压心脏", "hypertensive heart"),
    ("高血压", "hypertension"),
    ("肾脏", "renal"),
    ("稳定性心绞痛", "stable angina"),
    ("心肌梗死", "myocardial infarction"),
    ("呼吸心跳骤停", "cardiopulmonary arrest"),
    ("呼吸衰竭", "respiratory failure"),
    ("型呼吸衰竭", "type respiratory failure"),
    ("不完全性肠梗阻", "incomplete intestinal obstruction"),
    ("肝功能不全", "hepatic insufficiency"),
    ("雷诺", "Raynaud"),
    ("闭塞", "occlusion"),
    ("脉管炎", "vasculitis"),
    ("主", "main"),
    ("溃疡", "ulcer"),
    ("糖尿", "diabetes"),
    ("皮质醇增多症", "Cushing"),
    ("库欣", "Cushing"),
    ("联合变性", "combined degeneration"),
    ("脑腱胆固醇沉着", "cerebrotendinous xanthomatosis"),
    ("认知障碍", "cognitive impairment"),
    ("平山", "Hirayama"),
    ("进行性核上性眼肌麻痹", "progressive supranuclear palsy"),
    ("斯蒂尔", "Steele"),
    ("里查森", "Richardson"),
    ("奥尔谢夫斯基", "Olszewski"),
    ("莫顿跖痛症", "Morton metatarsalgia"),
    ("前跖痛", "anterior metatarsalgia"),
    ("跟痛症", "calcanodynia"),
    ("痉挛性四肢瘫痪", "spastic quadriplegia"),
    ("不完全性瘫痪", "incomplete paralysis"),
    ("截瘫", "paraplegia"),
    ("痉挛性步态", "spastic gait"),
    ("发热", "fever"),
    ("多脏器功能衰竭", "multiple organ failure"),
    ("猝死", "sudden death"),
    ("硬脑膜外", "epidural"),
    ("硬脑膜下", "subdural"),
    ("硬膜下", "subdural"),
    ("蛛网膜下", "subarachnoid"),
    ("脑积水", "hydrocephalus"),
    ("中央管", "central canal"),
    ("中央", "central"),
    ("皮肌炎", "dermatomyositis"),
    ("全身性硬皮", "systemic scleroderma"),
    ("抗心磷脂抗体", "antiphospholipid antibody"),
    ("血友", "hemophilia"),
    ("动态未定或动态未知的", "uncertain behavior"),
    ("动态未定", "uncertain behavior"),
    ("孟氏", "Monteggia"),
    ("盖氏", "Galeazzi"),
    ("伸直型", "extension-type"),
    ("操作后伤口", "postoperative wound"),
    ("创伤后伤口", "post-traumatic wound"),
    ("伤口", "wound"),
    ("障碍", "malfunction"),
    ("引起的", "caused by"),
    ("紊乱", "disorder"),
    ("屈曲", "flexion"),
    ("伸", "extensor"),
    ("屈", "flexor"),
    ("长屈肌", "long flexor muscle"),
    ("长屈", "long flexor"),
    ("指屈肌", "finger flexor muscle"),
    ("指屈", "finger flexor"),
    ("指伸", "finger extensor"),
    ("肌性斜", "muscular torticollis"),
    ("混合型", "mixed-type"),
    ("侧弯", "lateral curvature"),
    ("后侧凸", "kyphoscoliosis"),
    ("后凸", "kyphosis"),
    ("源性", "-genic"),
    ("第一", "first"),
    ("第二", "second"),
    ("第5", "fifth"),
    ("第", ""),
    ("段", "segment"),
    ("性", ""),
    ("型", "type"),
    ("的", ""),
    ("有", ""),
    ("样", "-like"),
    ("部", "region"),
    ("区", "region"),
    ("壁", "wall"),
    ("膜", "membrane"),
    ("腔", "cavity"),
    ("瘤", "tumor"),
    ("层", "layer"),
    ("基底", "base"),
    ("干", "shaft"),
    ("下", "lower"),
    ("上", "upper"),
    ("底", "plantar"),
    ("经", "trans-"),
    ("亚", "sub-"),
    ("双", "bilateral"),
    ("袖", "cuff"),
    ("残留", "retained"),
    ("冻结肩", "frozen shoulder"),
    ("冻结", "frozen"),
    ("撞击", "impingement"),
    ("破裂", "rupture"),
    ("指", "finger"),
    ("趾", "toe"),
    ("多", "multiple"),
    ("烧伤", "burn"),
    ("烫伤", "scald"),
    ("三度", "third-degree"),
    ("裂伤", "laceration"),
    ("肌疝", "muscle hernia"),
    ("痣", "nevus"),
    ("痛", "pain"),
    ("炎", "inflammation"),
    ("症", "condition"),
    ("平", "flat"),
    ("环", "ring"),
]


def _translate_chinese(text: str) -> str:
    """Rule-based Chinese→English translation using longest-match dictionary."""
    if not text or not any('\u4e00' <= c <= '\u9fff' for c in text):
        return text  # already English or code-like

    result_parts: list[str] = []
    i = 0
    while i < len(text):
        matched = False
        # Try longest match first (up to 10 chars)
        for length in range(min(10, len(text) - i), 0, -1):
            substr = text[i:i + length]
            for zh, en in _ZH_EN:
                if substr == zh:
                    if result_parts and result_parts[-1] != " ":
                        result_parts.append(" ")
                    result_parts.append(en)
                    result_parts.append(" ")
                    i += length
                    matched = True
                    break
            if matched:
                break
        if not matched:
            ch = text[i]
            # Skip punctuation / brackets
            if ch in "[]【】（）()，,、。.：: \t\n/\\＋+":
                if result_parts and result_parts[-1] != " ":
                    result_parts.append(" ")
            elif '\u4e00' <= ch <= '\u9fff':
                # Unknown Chinese char – keep it (will be cleaned later)
                result_parts.append(ch)
            elif ch.isascii():
                result_parts.append(ch)
            i += 1

    translated = " ".join("".join(result_parts).split())  # normalise spaces

    # Title-case the first letter
    if translated:
        translated = translated[0].upper() + translated[1:]

    return translated


def build_icd_mapping() -> Tuple[Dict[str, str], Dict[str, str]]:
    """
    Build two dictionaries:
      code_to_english  – ICD code → English disease/condition name
      code_to_chapter  – ICD code → chapter English name

    Covers all 1 000 benchmark codes (domain_by_class in {ID, OOD}).
    """
    # 1. Load benchmark codes
    split_df = pd.read_csv(_SPLIT_STATS, encoding="utf-8-sig")
    bench = split_df[split_df["domain_by_class"].isin(["ID", "OOD"])].copy()
    bench_codes = set(bench["code"].tolist())

    # 2. Load code → Chinese name mapping
    cc = pd.read_csv(_CODE_COUNTS)
    code_to_zh: Dict[str, str] = {}
    for _, row in cc.iterrows():
        code = str(row["出院诊断编码"]).strip()
        name = str(row["最常见对应诊断"]).strip()
        code_to_zh[code] = name

    # 3. Build English mapping
    code_to_english: Dict[str, str] = {}
    for code in sorted(bench_codes):
        # a) hard-coded override?
        if code in _HARDCODED:
            code_to_english[code] = _HARDCODED[code]
            continue

        # b) get Chinese name
        zh_name = code_to_zh.get(code, "")

        # If the "Chinese name" is just the code itself (or close), treat as missing
        if not zh_name or zh_name.lower().replace("x", "X") == code.lower().replace("x", "X"):
            # Fall back to hardcoded or produce a generic label
            if code in _HARDCODED:
                code_to_english[code] = _HARDCODED[code]
            else:
                # Derive from chapter
                ch = code[0].upper() if code else "?"
                chapter = _CHAPTER_MAP.get(ch, "Other")
                code_to_english[code] = f"{chapter} ({code})"
            continue

        # c) translate Chinese → English
        en = _translate_chinese(zh_name)
        code_to_english[code] = en

    # 4. Build chapter mapping
    code_to_chapter: Dict[str, str] = {}
    for code in sorted(bench_codes):
        ch = code[0].upper() if code else "?"
        code_to_chapter[code] = _CHAPTER_MAP.get(ch, "Other")

    return code_to_english, code_to_chapter


if __name__ == "__main__":
    m, c = build_icd_mapping()
    print(f"Mapped {len(m)} codes")
    for k, v in list(m.items())[:20]:
        print(f"  {k}: {v}")
    print(f"\nChapter mapping: {len(c)} codes")
    for k, v in list(c.items())[:5]:
        print(f"  {k}: {v}")
